name: concurrent ci/cd for testing

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: copying the repo for the runner ...
        uses: actions/checkout@v4

      - name: setting up python environment ...
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: installing dependencies from requirements.txt ...
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: running testing with unittest
        # -s flag is the path to the repo
        # -p flag is to run specific files
        # -m is to run a specific module, in this case, unittests
        run: python -m unittest discover -s tests -p "*.py"
