name: linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: copying the repo for the runner ...
        uses: actions/checkout@v4

      - name: setting up python environment ...
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev libjpeg-dev zlib1g-dev libfreetype6-dev

      - name: installing dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=pillow -r requirements.txt
          echo "MONGO_URI is $MONGO_URI"
      
      - name: finally running linting ...
        run: flake8

      
