name: testing and coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: copying the repo for the runner ...
        uses: actions/checkout@v4

      - name: setting up python environment ...
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: installing dependencies from requirements.txt ...
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: running all test files then coverage
        # -s flag is the path to the repo
        # -p flag is to run specific files
        # -m is to run a specific module, in this case, unittests
        run: |
          coverage run -m unittest discover -s tests -p "*.py"
          coverage report
          coverage html
