name: testing and coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: copying the repo for the runner ...
        uses: actions/checkout@v4

      - name: setting up python environment ...
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: installing dependencies from requirements.txt ...
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        name: mongodb debugging
        run: echo "MONGO_URI is $MONGO_URI"
        env:
          MONGO_URI: mongodb://localhost:27017/testdb

      - name: running all test files then coverage
        # -s is repo path, -p is file running, -m is unittests module
        run: |
          coverage run -m unittest discover -s tests -p "*.py"
          coverage report
          coverage html

      # - name: Upload coverage reports
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-report
      #     path: coverage-html/
