name: testing and coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: APP-DATABASE
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: copying the repo for the runner ...
        uses: actions/checkout@v4

      - name: setting up python environment ...
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"

      - name: installing dependencies from requirements.txt ...
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: running all test files then coverage
        # -s flag is the path to the repo
        # -p flag is to run specific files
        # -m is to run a specific module, in this case, unittests
        run: |
          coverage run -m unittest discover -s tests -p "*.py"
          coverage report
          coverage html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-html/
